<template>
    <div class="row">
        <div class="col-12 col-xs-12 col-sm-12 col-md-3 q-pa-sm">
            <q-card
                flat
                class="my-card bg-white"
            >
                <q-card-section>
                    <span class="text-h6 text-bold">Available Reports</span><br/>
                    <span class="text-caption text-grey">Reports available to be generated by the system</span><br/>
                    <q-separator /><br />
                    <q-tree
                        :nodes="reportTypes"
                        node-key="label"
                        default-expand-all
                        no-connectors
                        selected-color="primary"
                        v-model:selected="selected"
                    >
                        <template v-slot:default-header="prop">
                            <div class="row items-center">
                                <q-icon :name="prop.node.icon || 'share'" color="orange" size="28px" class="q-mr-sm" />
                                <div class="text-weight-bold">{{ prop.node.label }}</div>
                            </div>
                        </template>
                    </q-tree>

                </q-card-section>
            </q-card>
        </div>
        <div class="col-12 col-xs-12 col-sm-12 col-md-9 q-pa-sm">
            <q-card
                flat
                class="my-card bg-white"
            >
                <q-card-section>
                    <span class="text-h6 text-bold">Report Information & Filter</span><br/>
                    <span class="text-caption text-grey">Reports available to be generated by the system</span><br/>
                    <q-separator /><br/>
                    <q-banner inline-actions rounded class="bg-green text-white">
                        <span class="text-h6 text-bold">Generate {{selected}}</span>
                    </q-banner><br/>
                    <div class="row">
                        <div class="col col-md-3 q-pa-sm">
                            <q-input
                                class="q-mb-sm"
                                type="date"
                                outlined
                                v-model="dateSelected.from"
                                label="From"
                                stack-label
                                dense
                            />
                        </div>
                        <div class="col col-md-3 q-pa-sm">
                            <q-input
                                class="q-mb-sm"
                                type="date"
                                outlined
                                v-model="dateSelected.to"
                                label="To"
                                stack-label
                                dense
                            />
                        </div>
                        <div v-if="statusOpt.length !== 0" class="col col-md-3 q-pa-sm">
                            <q-select
                                dense
                                outlined
                                v-model="formFilter.status"
                                :options="statusOpt"
                                use-chips
                                stack-label
                                label="Status"
                            />
                        </div>
                        <div v-if="typeOpt.length !== 0" class="col col-md-3 q-pa-sm">
                            <q-select
                                dense
                                outlined
                                v-model="formFilter.type"
                                :options="typeOpt"
                                use-chips
                                stack-label
                                label="Transaction Type"
                            />
                        </div>

                        <div class="col-12 col-md-12"><q-separator /><br/></div>
                        <div class="col col-md-12 text-right">
                            <q-btn
                                dense
                                icon="table_chart"
                                color="primary"
                                class="q-pl-md q-pr-md q-mr-sm"
                                label="Show Preview"
                                :disabled="!showTransacDisable"
                                @click="showPreview"
                            />

                        </div>
                    </div>
                </q-card-section>
            </q-card>
        </div>
        <div class="col-12 col-xs-12 col-sm-12 col-md-12 q-pa-sm">
            <q-card
                flat
                class="my-card bg-white"
            >
                <q-card-section>
                    <span class="text-h6 text-bold">Report Preview</span><br/>
                    <span class="text-caption text-grey">Reports available to be generated by the system</span>
                    <div v-if="reportShowResult">
                        <br/>
                        <br/>
                        <q-table
                            :rows="rowResult"
                            :columns="rowColumns"
                            row-key="orNumber"
                            :rows-per-page-options="[20]"
                        >
                          <template v-slot:body-cell-items="props">
                              <q-td :props="props">
                                {{ generateItemList(props.row.items) }}
                              </q-td>
                          </template>
                          <template v-slot:top-right>
                            <q-btn
                              dense
                              icon="file_download"
                              color="green"
                              class="q-pl-md q-pr-md"
                              label="Export CSV"
                              :disabled="!reportShowResult"
                              @click="generateReport"
                            />
                            <q-btn
                              dense
                              icon="file_download"
                              color="green"
                              class="q-pl-md q-pr-md q-ml-sm"
                              label="Export PDF"
                              :disabled="!reportShowResult"
                              @click="exportPDF"
                            />
                          </template>
                        </q-table>
                    </div>
                </q-card-section>
            </q-card>
        </div>
    </div>
</template>

<script>
import moment from 'moment';
import { LocalStorage, exportFile } from 'quasar'
import noData from '../Templates/NoData.vue';
import jwt_decode from 'jwt-decode'
import { api } from 'boot/axios'

export default {
    name: 'ReportGenerator',
    data(){
        return {

            rowResult: [],
            rowColumns: [],

            rowSchema: [],
            dataReport: [],

            reportShowResult: false,
            dateSelected: {
                from: "",
                to: ""
            },
            formFilter: {
                status: null,
                type: null
            },
            selected: "10 Column Report",
            reportTypes: [
                {
                    label: 'Report List',
                    icon: 'folder',
                    header: 'root',
                    children: [
                        // {
                        //     label: 'Sales Report',
                        //     icon: 'description',
                        //     header: 'generic',
                        //     api: "generate/report/sales",
                        //     key: "salesColumn"
                        // },
                        {
                            label: 'Auction Item Report',
                            icon: 'description',
                            header: 'generic',
                            api: "generate/report/auctions",
                            key: "acutionColumn"
                        },
                        // {
                        //     label: 'Expired Loans Report',
                        //     icon: 'description',
                        //     header: 'generic',
                        //     api: "generate/report/sales",
                        //     key: "expiredColumn"
                        // },
                        {
                            label: '10 Column Report',
                            header: 'generic',
                            body: 'story',
                            icon: 'description',
                            api: "generate/report/10columns",
                            pdfprint: "generate/print/10columns",
                            key: ""
                        },
                        {
                            label: '24 Column Report',
                            header: 'generic',
                            icon: 'description',
                            api: "generate/report/24columns",
                            pdfprint: "generate/print/24columns",
                            key: ""
                        }
                    ]
                }
            ],


        }
    },
    components: {
        noData
    },
    methods: {
        moment,
        showPreview(){
            let getApiUrl = this.reportTypes[0]
                            .children
                            .filter(el => {
                                return el.label === this.selected
                            });
            getApiUrl = getApiUrl.length > 0 ? {...getApiUrl[0]} : false;

            let payload = {
              ...this.dateSelected,
              status: this.formFilter.status?.value || 1,
              type: this.formFilter.type?.value || 0,
            }

            api.post(getApiUrl.api, payload).then((response) => {
                const data = {...response.data};

                if(!data.error){
                    this.rowColumns = data.columns
                    this.rowResult = data.list
                    this.reportShowResult = true
                } else {
                    this.$q.notify({
                        color: 'negative',
                        position: 'top-right',
                        title:data.title,
                        message: this.$t(`errors.${data.error}`),
                        icon: 'report_problem'
                    })
                }

            })

        },
        checkTypeOf(value){
            return typeof value
        },
        generateItemList(list){
          let res = [];
          list.forEach(el => {
            let str = `${el.qty} ${el.unit.value} ${el.type.value}, ${el.description || 'N/A'}, ${el.weight}/${el.property} with ${el.remarks || ''}`;
            res.push(str);
          });

          return res.join(", ")
        },
        wrapCsvValue (val, formatFn, row) {
            let formatted = formatFn !== void 0
                ? formatFn(val, row)
                : val

            formatted = formatted === void 0 || formatted === null
                ? ''
                : String(formatted)

            formatted = formatted.split('"').join('""')
            /**
             * Excel accepts \n and \r in strings, but some other CSV parsers do not
             * Uncomment the next two lines to escape new lines
             */
            // .split('\n').join('\\n')
            // .split('\r').join('\\r')

            return `"${formatted}"`
        },
        async exportPDF(){
          let getApiUrl = this.reportTypes[0]
                          .children
                          .filter(el => {
                              return el.label === this.selected
                          });
          getApiUrl = getApiUrl.length > 0 ? {...getApiUrl[0]} : false;
          const link = document.createElement('a');
          link.id = "downloadResult";
          link.href = `${process.env.API_BASE}/${getApiUrl.pdfprint}/${this.dateSelected.from}`;
          link.target = "_blank";

          link.click();
        },
        async generateReport(){
            this.rowColumns
            this.rowResult
            // naive encoding to csv format
            const content = [this.rowColumns.map(col => this.wrapCsvValue(col.label))].concat(
            this.rowResult.map(row => this.rowColumns.map(col => this.wrapCsvValue(
                typeof col.field === 'function'
                ? col.field(row)
                : row[ col.field === void 0 ? col.name : col.field ],
                col.format,
                row
            )).join(','))
            ).join('\r\n')

            // Generate Filename
            let filename = "";
            if(this.dateSelected.from === this.dateSelected.to){
                filename = `${this.selected}_${this.dateSelected.from}`
            } else {
                filename = `${this.selected}_${this.dateSelected.from}_${this.dateSelected.to}`
            }

            // export report
            exportFile(
                filename,
                content,
                'text/csv'
            )
        }
    },
    computed: {
        user: function(){
            let profile = LocalStorage.getItem('userData');
            return jwt_decode(profile);
        },
        showTransacDisable(){
            let getApiUrl = this.reportTypes[0]
                            .children
                            .filter(el => {
                                return el.label === this.selected
                            });
           return getApiUrl.length > 0;
        },
        statusOpt(){
            let opt = [];
            if(this.selected === "Sales Report"){
                opt = [
                    {label: 'Recorded', value: 0},
                    {label: 'Reported', value: 1},
                ]
            } else if(this.selected === "Auction Item Report") {
                opt = [
                    {label: 'Listed', value: 0},
                    {label: 'Sold', value: 1},
                ]
            }
            return opt
        },
        typeOpt(){
            let opt = [];
            if(this.selected === "Sales Report"){
                opt = [
                    {label: 'Sales', value: 0},
                    {label: 'Loans', value: 1},
                    {label: 'Expenses', value: 3},
                    {label: 'Charges', value: 4},
                ]
            }
            return opt
        }
    }
}
</script>
<style scoped>
.my-card{
    border-radius: 15px;
    box-shadow: 0px 0px 3px -2px !important;
}
</style>
